<?php
$typeArr[1] = '产品中心';
$typeArr[2] = '优雅系列办公灯具';
$typeArr[3] = '魔术系列薄板光源';
$typeArr[4] = '瑞安系列LED天花';
$typeArr[5] = '焦点系列轨道射灯';
$typeArr[6] = '克莱恩系列LED灯管';
$typeArr[7] = 'CLEVER SIGHT智能控制器';
$typeArr[8] = '智能照明';
$typeArr[9] = '系统组成';
$typeArr[10] = '系统功能';
$typeArr[11] = '系统的优势';
$typeArr[12] = '适用环境';
$typeArr[13] = '应用范例';
$typeArr[14] = '百货商场照明应用场景';
$typeArr[15] = '酒店照明应用场景';
$typeArr[16] = '学校照明应用场景';
$typeArr[17] = '家庭照明应用场景';
$typeArr[18] = '办公区照明应用场景';
$typeArr[19] = '关于我们';
$typeArr[20] = '公司介绍';
$typeArr[21] = '联系方式';
$typeArr[22] = '新闻动态';
$typeArr[23] = '公司新闻';
$typeArr[24] = '行业动态';
$typeArr[25] = '幻灯';
?>