<?php
$z[0]=Array("field","",274,303);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",341,400);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",411,430);
$z[2][4]['name']="title";
$z[3]=Array("global","",431,457);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",6206,6241);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",6536,6594);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n              <li id=\"item-520\" class=\"item-520\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",6748,7038);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[7]=Array("field","",7703,7732);
$z[7][4]['name']="position";
$z[8]=Array("field","",7866,7885);
$z[8][4]['name']="title";
$z[9]=Array("field","",8066,8122);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("adminname","",8151,8168);
$z[11]=Array("field","",8232,8250);
$z[11][4]['name']="body";
$z[12]=Array("include","",9516,9553);
$z[12][4]['filename']="footer.htm";

?>