<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,366);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",406,464);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",6209,6244);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",6539,6597);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n              <li id=\"item-520\" class=\"item-520\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",6751,7042);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[7]=Array("field","",7707,7736);
$z[7][4]['name']="position";
$z[8]=Array("field","",7796,7817);
$z[8][4]['name']="content";
$z[9]=Array("include","",9065,9102);
$z[9][4]['filename']="footer.htm";

?>