<?php
$z[0]=Array("global","",274,301);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",339,369);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",380,406);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n        <li id=\"item-512\" class=\"item-512\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",7477,7759);
$z[3][4]['row']="5";
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li class='current active'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[4]=Array("arclist","\r\n            <div style=\"position: absolute; left: 0px; top: 0px; opacity: 0; z-index: 1;\" id=\"[field:id/]\" class=\"item active\"><span class=\"item-content\" style=\"background-image:url([field:litpic/])\"> </span></div>\r\n            ",9028,9310);
$z[4][4]['typeid']="25";
$z[4][4]['row']="5";
$z[5]=Array("include","",11277,11314);
$z[5][4]['filename']="footer.htm";

?>