<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,366);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",406,464);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",6446,6481);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",6776,6834);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n              <li id=\"item-520\" class=\"item-520\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",6988,7279);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[7]=Array("field","",7944,7973);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n            <div style=\"margin-left:0;\" class=\"list-item list-item-n3\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"list-img-area list-img-n3\">\r\n              <div class=\"list-img\"> <img style=\"width: 174px; height: 130px;\" src=\"[field:picname/]\"> </div>\r\n              </a> <a href=\"[field:arcurl/]\" class=\"list-title\" title=\"[field:title/]\">[field:title/]</a></div>\r\n            ",8052,8483);
$z[8][4]['pagesize']="9";
$z[9]=Array("pagelist","",8716,8794);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="10";
$z[10]=Array("include","",10028,10065);
$z[10][4]['filename']="footer.htm";

?>