<?php
$z[0]=Array("field","",266,295);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",333,392);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",403,422);
$z[2][4]['name']="title";
$z[3]=Array("global","",423,449);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",6387,6422);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",6717,6775);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n              <li id=\"item-520\" class=\"item-520\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",6929,7221);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[7]=Array("field","",7886,7915);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                    <li><span class=\"v3\"><a href=\"[field:arcurl/]\">[field:title/]</a></span><span class=\"v4\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n                    ",8149,8379);
$z[8][4]['pagesize']="14";
$z[9]=Array("pagelist","",8704,8782);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="10";
$z[10]=Array("include","",10016,10053);
$z[10][4]['filename']="footer.htm";

?>